### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by worksofliam** [starbuck5250/SEUEXIT#4]
Hi,

I'd like to make a fork of this to allow it to be built with the package manager.

Is this ok?

Thanks,
Liam

**Comment by aaronbartell** [comment]
So polite :-)  It's under MIT so I say fork and pull and then Buck can review.

**Comment by starbuck5250** [comment]
Is it OK?  Heck, it's encouraged!

**Comment by worksofliam** [comment]
Hi,

I accidentally made the changes without a pull request + I already committed them.

Could you possibly make me a contributor so I am able to push them commits? :-)

Thanks,
Liam

**Comment by starbuck5250** [comment]
Absolutely!  Think of this as a test bed for hammering out the processes an RPG programmer will need in order to use GitHub.  Best guess is that no one will actually use this particular project; it has such a limited audience.  Perfect for puttering around though!

**Comment by worksofliam** [comment]
Okay. Made the first commit to remove the timestamps, they were annoying.

Now I'll get on with adding the build file, then I actually need to make the Package Manager open-source.

**Comment by worksofliam** [comment]
Hi,

SEUEXIT now builds successfully with one command, which is great.

Now I need to make the package manager open-source.

![image](https://cloud.githubusercontent.com/assets/3708366/15449574/617da140-1f79-11e6-9ebd-cb9fc7b79598.png)
